;; IDLWAVE paths
;; Created Fri Mar 20 14:49:19 2015


(setq idlwave-system-directory "/usr/local/exelis/idl84/")

(setq idlwave-path-alist
    '(
      ("/usr/local/exelis/idl84/lib/bridges/")
      ("/usr/local/exelis/idl84/lib/datatypes/")
      ("/usr/local/exelis/idl84/lib/dicomex/")
      ("/usr/local/exelis/idl84/lib/enterprise/ese/")
      ("/usr/local/exelis/idl84/lib/graphics/")
      ("/usr/local/exelis/idl84/lib/hook/")
      ("/usr/local/exelis/idl84/lib/imsl/")
      ("/usr/local/exelis/idl84/lib/itools/components/")
      ("/usr/local/exelis/idl84/lib/itools/framework/")
      ("/usr/local/exelis/idl84/lib/itools/ui_widgets/")
      ("/usr/local/exelis/idl84/lib/itools/")
      ("/usr/local/exelis/idl84/lib/obsolete/")
      ("/usr/local/exelis/idl84/lib/utilities/")
      ("/usr/local/exelis/idl84/lib/wavelet/data/")
      ("/usr/local/exelis/idl84/lib/wavelet/source/")
      ("/usr/local/exelis/idl84/lib/")
      ("/usr/local/exelis/idl84/examples/data/")
      ("/usr/local/exelis/idl84/examples/demo/demodata/")
      ("/usr/local/exelis/idl84/examples/demo/demoslideshows/slideshowsrc/")
      ("/usr/local/exelis/idl84/examples/demo/demosrc/")
      ("/usr/local/exelis/idl84/examples/demo/")
      ("/usr/local/exelis/idl84/examples/doc/bridges/")
      ("/usr/local/exelis/idl84/examples/doc/dicom/")
      ("/usr/local/exelis/idl84/examples/doc/file_io/")
      ("/usr/local/exelis/idl84/examples/doc/image/")
      ("/usr/local/exelis/idl84/examples/doc/itools/")
      ("/usr/local/exelis/idl84/examples/doc/language/")
      ("/usr/local/exelis/idl84/examples/doc/objects/")
      ("/usr/local/exelis/idl84/examples/doc/plot/")
      ("/usr/local/exelis/idl84/examples/doc/sdf/")
      ("/usr/local/exelis/idl84/examples/doc/shaders/")
      ("/usr/local/exelis/idl84/examples/doc/signal/")
      ("/usr/local/exelis/idl84/examples/doc/utilities/")
      ("/usr/local/exelis/idl84/examples/doc/widgets/")
      ("/usr/local/exelis/idl84/examples/HP_TIFF/")
      ("/usr/local/exelis/idl84/examples/imsl/")
      ("/usr/local/exelis/idl84/examples/misc/")
      ("/usr/local/exelis/idl84/examples/mjpeg2000/")
      ("/usr/local/exelis/idl84/examples/ogc/wcs/")
      ("/usr/local/exelis/idl84/examples/ogc/wms/")
      ("/usr/local/exelis/idl84/examples/widgets/wexmast/")
      ("/usr/local/exelis/idl84/examples/widgets/")
      ("/usr/local/exelis/idl84/examples/")
      ("/usr/local/exelis/idl84/idlde/plugins/com.rsi.idldt_8.4.0/icons/")
      ("/Users/ZhouYf/IDL/__MACOSX/idp3_07JAN2014/")
      ("/Users/ZhouYf/IDL/__MACOSX/ua_lib/ua_fits/")
      ("/Users/ZhouYf/IDL/__MACOSX/ua_lib/")
      ("/Users/ZhouYf/IDL/coyote/public/" lib)
      ("/Users/ZhouYf/IDL/coyote/" lib)
      ("/Users/ZhouYf/IDL/idp3_07JAN2014/ua_lib/ua_fits/")
      ("/Users/ZhouYf/IDL/idp3_07JAN2014/ua_lib/")
      ("/Users/ZhouYf/IDL/idp3_07JAN2014/")
      ("/Users/ZhouYf/IDL/misc/")
      ("/Users/ZhouYf/IDL/pro/astro/" lib)
      ("/Users/ZhouYf/IDL/pro/astrom/" lib)
      ("/Users/ZhouYf/IDL/pro/cmtotal/")
      ("/Users/ZhouYf/IDL/pro/database/" lib)
      ("/Users/ZhouYf/IDL/pro/disk_io/" lib)
      ("/Users/ZhouYf/IDL/pro/fits/" lib)
      ("/Users/ZhouYf/IDL/pro/fits_bintable/" lib)
      ("/Users/ZhouYf/IDL/pro/fits_table/" lib)
      ("/Users/ZhouYf/IDL/pro/idlphot/" lib)
      ("/Users/ZhouYf/IDL/pro/image/" lib)
      ("/Users/ZhouYf/IDL/pro/jhuapl/" lib)
      ("/Users/ZhouYf/IDL/pro/math/" lib)
      ("/Users/ZhouYf/IDL/pro/misc/" lib)
      ("/Users/ZhouYf/IDL/pro/plot/" lib)
      ("/Users/ZhouYf/IDL/pro/robust/" lib)
      ("/Users/ZhouYf/IDL/pro/sdas/" lib)
      ("/Users/ZhouYf/IDL/pro/sockets/" lib)
      ("/Users/ZhouYf/IDL/pro/structure/" lib)
      ("/Users/ZhouYf/IDL/pro/tv/" lib)
      ("/Users/ZhouYf/IDL/pro/" lib)
      ("/Users/ZhouYf/IDL/")))
